EditorJournal/Areas/Admin/Controllers/CompanyController.cs
using EditorJournal.Modals;
using Microsoft.AspNetCore.Mvc;
using EditorJournal.data.Repo.IRepo;

namespace EditorJournal.Areas.Admin.Controllers
{
    [Area("Admin")]
   
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;
       
        public CompanyController(IUnitOfWork Debase, IWebHostEnvironment webHostEnvironment)
        {
            _UnitOfWork = Debase;
            
        }
        public IActionResult Index() 
        {
            List<Company> CompanyList = _UnitOfWork.CompanyRepo.GetAll().ToList();
           
            return View(CompanyList);
        }
        public IActionResult CreateUpdate(int? id)
        {



            if (id == null || id==0)
            {
                return View(new Company());
            } else
            {
                Company Company = _UnitOfWork.CompanyRepo.Get(u => u.Id == id);
                if (Company == null)
                {
                    return NotFound(); 
                }
                return View(Company);
                
               
            }
          
           
        }
        [HttpPost]
        public IActionResult CreateUpdate(Company obj)
        {
            if (ModelState.IsValid)
            {
              
                
                if (obj.Id == 0)
                {
                    
                    _UnitOfWork.CompanyRepo.Add(obj);
                }
                else
                {
                   
                    var currentCompany = _UnitOfWork.CompanyRepo.Get(u => u.Id == obj.Id);
                    if (currentCompany != null)
                    {
                        currentCompany.StreetAddress = obj.StreetAddress;
                        currentCompany.City = obj.City;
                        currentCompany.PhoneNumber = obj.PhoneNumber;
                        currentCompany.Name = obj.Name;
                        currentCompany.State = obj.State;
                        currentCompany.PostalCode = obj.PostalCode;
                       
                        _UnitOfWork.CompanyRepo.Update(currentCompany);
                    }
                    else
                    {
                      
                        return NotFound();
                    }
                }

                _UnitOfWork.Save();
                //TempData["success"] = obj.Id == 0 ? "New Company created Successfully." : "Company updated Successfully.";
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        public IActionResult Delete(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Company CompanyFromDebase = _UnitOfWork.CompanyRepo.Get(u => u.Id == id);
            if (CompanyFromDebase == null)
            {
                return NotFound();
            }
            return View(CompanyFromDebase);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteObject(int id)
        {
            Company Object = _UnitOfWork.CompanyRepo.Get(u => u.Id == id);
            if (Object == null)
            {
                return NotFound();
            }
            _UnitOfWork.CompanyRepo.Remove(Object);


            _UnitOfWork.Save();
            TempData["success"] = "Company deleted Successfully.";
            return RedirectToAction("Index");


        }
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> CompanyList = _UnitOfWork.CompanyRepo.GetAll().ToList();
            return Json(new { data = CompanyList });
        }
    
    }

}

EditorJournal/Areas/Admin/Controllers/ItemsController.cs
using EditorJournal.Modals;
using Microsoft.AspNetCore.Mvc;
using EditorJournal.data.Repo.IRepo;
using EditorJournal.Modals.ViewModels;

namespace EditorJournal.Areas.Admin.Controllers
{
    [Area("Admin")]
 
    public class ItemsController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;
        private readonly IWebHostEnvironment _WebHostEnvironment;
        public ItemsController(IUnitOfWork Debase, IWebHostEnvironment webHostEnvironment)
        {
            _UnitOfWork = Debase;
            _WebHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index() 
        {
            List<Item> ItemList = _UnitOfWork.ItemsRepo.GetAll().ToList();
           
            return View(ItemList);
        }
        public IActionResult CreateUpdate(int? id)
        {

            ItemVM ItemVM = new()
            {
                Item = new Item()
            };
            if(id==null || id == 0)
            {
                return View(ItemVM);
            }else
            {
                ItemVM.Item = _UnitOfWork.ItemsRepo.Get(u => u.Id == id);
                return View(ItemVM);

            }
          
           
        }
        [HttpPost]
        public IActionResult CreateUpdate(ItemVM obj, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string WwwRootPath = _WebHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string pathToImage = Path.Combine(WwwRootPath, "Images", "ResultedImage", fileName);
                    using (var fileStream = new FileStream(pathToImage, FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    obj.Item.ImageUrl = Path.Combine("Images", "ResultedImage", fileName);
                }

                
                if (obj.Item.Id == 0)
                {
                    
                    _UnitOfWork.ItemsRepo.Add(obj.Item);
                }
                else
                {
                   
                    var currentItem = _UnitOfWork.ItemsRepo.Get(u => u.Id == obj.Item.Id);
                    if (currentItem != null)
                    {
                        currentItem.Description = obj.Item.Description;
                        currentItem.Genre=obj.Item.Genre;
                        currentItem.Price = obj.Item.Price;
                        currentItem.Title = obj.Item.Title;
                        currentItem.AuthorName = obj.Item.AuthorName;
                        if (file != null)
                        {
                            currentItem.ImageUrl = obj.Item.ImageUrl;
                          
                        }
                        _UnitOfWork.ItemsRepo.update(currentItem);
                    }
                    else
                    {
                      
                        return NotFound();
                    }
                }

                _UnitOfWork.Save();
                //TempData["success"] = obj.Id == 0 ? "New Item created Successfully." : "Item updated Successfully.";
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        public IActionResult Delete(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Item ItemFromDebase = _UnitOfWork.ItemsRepo.Get(u => u.Id == id);
            if (ItemFromDebase == null)
            {
                return NotFound();
            }
            return View(ItemFromDebase);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteObject(int id)
        {
            Item itemObj = _UnitOfWork.ItemsRepo.Get(u => u.Id == id);
            if (itemObj == null)
            {
                return NotFound();
            }
            _UnitOfWork.ItemsRepo.Remove(itemObj);


            _UnitOfWork.Save();
            TempData["success"] = "Item deleted Successfully.";
            return RedirectToAction("Index");


        }
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Item> ItemList = _UnitOfWork.ItemsRepo.GetAll().ToList();
            return Json(new { data = ItemList });
        }
       

    }

}

EditorJournal/Areas/Customer/Controllers/CartController.cs
using EditorJournal.data.Repo.IRepo;
using EditorJournal.Modals;
using EditorJournal.Modals.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace EditorJournal.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
        public IUnitOfWork _UnitOfWork { get; set; }
        [BindProperty]
        public ShoppingCartVM ShoppingCartVM { get; set; }

        public CartController(IUnitOfWork unitOfWork)
        {
            _UnitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCartVM = new()
            {
                ShoppingCartLists = _UnitOfWork.ShoppingCartRepo.GetAll(u => u.AppUserId == userId, includeProperties: "Item"),
                OrderHeader = new()
            };
            foreach (var item in ShoppingCartVM.ShoppingCartLists)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += item.Count * item.Item.Price;
            }
            return View(ShoppingCartVM);
        }
        [HttpGet]
        public IActionResult Summary()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            ShoppingCartVM = new()
            {
                ShoppingCartLists = _UnitOfWork.ShoppingCartRepo.GetAll(u => u.AppUserId == userId, includeProperties: "Item"),
                OrderHeader = new()
            };
            ShoppingCartVM.OrderHeader.AppUser = _UnitOfWork.AppUserRepo.Get(u => u.Id == userId);
            ShoppingCartVM.OrderHeader.PhoneNumber = ShoppingCartVM.OrderHeader.AppUser.PhoneNumber;
            ShoppingCartVM.OrderHeader.Address = ShoppingCartVM.OrderHeader.AppUser.Address;
            ShoppingCartVM.OrderHeader.Name = ShoppingCartVM.OrderHeader.AppUser.Name;

            foreach (var item in ShoppingCartVM.ShoppingCartLists)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += item.Count * item.Item.Price;
            }
            return View(ShoppingCartVM);
        }

        [HttpPost]
        [ActionName("Summary")]
        public IActionResult SummaryPOST()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCartVM = new()
            {
                ShoppingCartLists = _UnitOfWork.ShoppingCartRepo.GetAll(u => u.AppUserId == userId, includeProperties: "Item"),
                OrderHeader = new OrderHeader()
            };
                         
            

            ShoppingCartVM.OrderHeader.AppUserId = userId;
            AppUser appUser = _UnitOfWork.AppUserRepo.Get(u => u.Id == userId);

            foreach (var item in ShoppingCartVM.ShoppingCartLists)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += item.Count * item.Item.Price;
            }

            if (appUser.CompanyID.GetValueOrDefault() == 0)
            {
                ShoppingCartVM.OrderHeader.PaymentStatus = StaticDetails.PaymentStatusPending;
                ShoppingCartVM.OrderHeader.OrderStatus = StaticDetails.StatusPending;
            }
            else
            {
                ShoppingCartVM.OrderHeader.PaymentStatus = StaticDetails.PaymentStatusDelayedForFarPayment;
                ShoppingCartVM.OrderHeader.OrderStatus = StaticDetails.PaymentStatusApproved;
            }
            _UnitOfWork.OrderHeaderRepo.Add(ShoppingCartVM.OrderHeader);
            _UnitOfWork.Save();
            foreach (var item in ShoppingCartVM.ShoppingCartLists)
            {
                OrderDetail orderDetail = new()
                {
                    ItemId = item.ItemId,
                    OrderHeaderId = ShoppingCartVM.OrderHeader.Id,
                    Price = item.Item.Price,
                    Count = item.Count
                };
                _UnitOfWork.OrderDetailRepo.Add(orderDetail);
                _UnitOfWork.Save();
            }

            return RedirectToAction(nameof(OrderConfirmation), new { id = ShoppingCartVM.OrderHeader.Id });
        }

        public IActionResult OrderConfirmation(int id)
        {
            return View(id);
        }

        public IActionResult Decrement(int cartId)
        {
            var cartFromDb = _UnitOfWork.ShoppingCartRepo.Get(u => u.Id == cartId);
            cartFromDb.Count -= 1;
            if (cartFromDb.Count > 0)
            {
                _UnitOfWork.ShoppingCartRepo.Update(cartFromDb);
            }
            _UnitOfWork.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Increment(int cartId)
        {
            var cartFromDb = _UnitOfWork.ShoppingCartRepo.Get(u => u.Id == cartId);
            cartFromDb.Count += 1;
            if (cartFromDb.Count > 0)
            {
                _UnitOfWork.ShoppingCartRepo.Update(cartFromDb);
            }
            _UnitOfWork.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int cartId)
        {
            var cartFromDb = _UnitOfWork.ShoppingCartRepo.Get(u => u.Id == cartId);
            _UnitOfWork.ShoppingCartRepo.Remove(cartFromDb);
            _UnitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
    }
}

EditorJournal/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> _userManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Crud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="//cdn.datatables.net/2.0.3/css/dataTables.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Crud.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">CURDAPP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(StaticDetails.RoleAdmin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Contents
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Items" asp-action="Index">Items</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                </div>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                <img src="/Images/ResultedImage/977d5f02-2a45-47b9-8f32-73fb7eba867d.png" alt="Alternate Text" style="width:1.5rem;" /> (0)
                            </a>
                        </li>
                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Crud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.datatables.net/2.0.3/js/dataTables.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/gbi7nxy3q9ynx27x96jq7jv2an68qfsx9uyo583658eyg4bv/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>